config/routes.rb
Champrater::Application.routes.draw do

  root 'site#index'

  get     'login' => 'session#new'
  post    'login' => 'session#create'
  delete  'logout' => 'session#destroy'
  get     'logout' => 'session#destroy'

  get 'privacy' => 'site#privacy'
  get 'terms' => 'site#terms'

  get 'reset/:code' => 'password#edit', as: :reset
  put 'reset/:code' => 'password#update'
  patch 'reset/:code' => 'password#update'

  get 'characters' => 'characters#index', as: :characters
  post 'characters' => 'characters#rating'
  patch 'characters' => 'characters#search' #, as: :charsearch

end

app/models/character.rb
class Character

  include Mongoid::Document
  include Mongoid::Timestamps



  field :name, type: String
  field :image, type: String
  field :votes, type: Integer
  field :total_score, type: Integer


  def update_count votes
    self.votes += 1
    self.total_score += votes.to_i
    self.save
  end

  def self.search(search)
    if search
      Character.where(name: /#{search}.*/i).first
    else
      Character.all.entries
    end
  end
end

app/models/concerns/password_resetter.rb
class PasswordResetter

  SUCCESS = "We'll send you an email with instrutions for resetting"
  NO_MAIL = "Unable to send email. Please notify webmaster"
  NO_SAVE = "Password reset failed. Please notify webmaster"
  NO_USER = "Unable to log you in. Please check your Email and Password again "

  def initialize(flash)
    @flash = flash
  end

  def handle_reset_request(params)
    if @user = User.find_by(email: params[:email])
      update_user_and_send_email
    else
      @flash.now[:alert] = NO_USER
    end
  end

  def update_user_and_send_email
    if @user.set_password_reset
      send_reset_email
    else
      @flash.now[:alert] = NO_SAVE
    end
  end

  def send_reset_email
    begin
      UserNotifier.reset_password(@user).deliver
      @flash.now[:notice] = SUCCESS
    rescue
      @flash.now[:alert] = NO_MAIL
    end
  end

end

app/models/concerns/user_authenticator.rb
class UserAuthenticator

  AUTH_FAILED = "Unable to log you into the system, please try again"

  def initialize(session, flash)
    @flash = flash
    @session = session
  end

  def authenticate_user(params)
    #email and password

    @flash.now[:alert] = AUTH_FAILED unless @user = User.authenticate(params[:email], params[:password])
    @user

  end


end

app/models/user.rb
require 'bcrypt'

PASSWORD_RESET_EXPIRES = 4

class User

  include Mongoid::Document
  include Mongoid::Timestamps

  attr_accessor :password, :password_confirmation


  field :email, type: String
  field :salt, type: String
  field :fish, type: String
  field :code, type: String
  field :expires_at, type: Time

  before_save :set_random_password, :encrypt_password
  validates :email, presence: true, uniqueness: {case_sensitive: false}
  validates :password, confirmation: true

  def self.authenticate email, password
    user = User.find_by email: email
    user if user and user.authenticate(password)
  end

  def self.find_by_code code
    if user = User.find_by({:code => code, :expires_at => {"$gte" => Time.now.gmtime}})
      user.set_expiration
    end
    user
  end

  def authenticate password
    self.fish == BCrypt::Engine.hash_secret(password, self.salt)
  end

  def set_password_reset
    self.code = SecureRandom.urlsafe_base64
    set_expiration
  end

  def set_expiration
    self.expires_at = PASSWORD_RESET_EXPIRES.hours.from_now
    self.save!
  end


  protected

    def set_random_password
      if self.fish.blank? and password.blank?
        self.salt = BCrypt::Engine.generate_salt
        self.fish = BCrypt::Engine.hash_secret(SecureRandom.base64(32), self.salt)
      end
    end

    def encrypt_password
      if password.present?
        self.salt = BCrypt::Engine.generate_salt
        self.fish = BCrypt::Engine.hash_secret(password, self.salt)
      end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  before_filter :make_action_mailer_user_request_host_and_protocol

  def is_authenticated?
    #check session hash for a :user_id (true/false)
    # not session[:user_id].nil?
    # redirect_to login_url if session[:user_id].nil?
    redirect_to login_url unless current_user
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  private

  def make_action_mailer_user_request_host_and_protocol
    ActionMailer::Base.default_url_options[:protocol] = request.protocol
    ActionMailer::Base.default_url_options[:host] = request.host_with_port
  end

end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

  # before_action :is_authenticated?

  def index
    @message = "hello"
    @character = Character.all.entries.sample
  end

  def rating
    @character = Character.find_by _id: params[:character_id]
    @character.update_count params[:rating]
    redirect_to(:back)
  end

  def vote
    @user = User.new

  end

  def search
    @character = Character.search params[:search]
    render :index
  end

  def show

  end

end

app/controllers/password_controller.rb
class PasswordController < ApplicationController

  def edit
    @user = User.find_by_code params[:code]
    redirect_to login_url, notice: "Your reset link has expired, Please generate a new one" unless @user
  end

  def update
    @user = User.find_by_code params[:code]

    if @user
    # if user is found
      if params[:user][:password].blank?
        @user.errors.add(:password, "This field can't be blank")
      elsif @user.update_attributes user_params
        render text: "Success!"
      else
        render text: "Failure!"
      end

    # otherwise show a message not found
    else
      render text: "No code found"
    end

  end

  private

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end


end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  # skip_before_action :verify_authenticity_token

  def new
    # @messages = flash.inspect
    # @messages = flash.map {| key, value| "#{key.capitalize}: #{value}"}.join(";")
    # render text: "Display the log in form."
    redirect_to root_url, notice: "You are logged in." if current_user
  end

  def create
    # @user = User.authenticate(params[:user][:email], params[:user][:password])
    user = User.find_by(email: params[:user][:email])
    password = params[:user][:password]


    if user and password.blank?
      user.set_password_reset
      UserNotifier.reset_password(user).deliver
      flash.now[:notice] = "We'll send you an email.."
      render :new
    elsif user and user.authenticate(password)
      session[:user_id] = user.id
      redirect_to characters_url
    else
      flash.now[:alert] = "Unable to log you in. Please check your email and password and try again."
      render :new
    end

  end

  def destroy
    session[:user_id] = nil
    # render text: "Log the user out."
    redirect_to login_url, notice: "You've successfully logged out."
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  before_action :is_authenticated?

  def index
    # render json: User.all.entries
    @users = User.all.entries
  end

  def privacy
  end

  def terms
  end

  def wdi
    @fuck = "you"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def average_score
    return 0 if @character.votes == 0

    return @character.total_score / @character.votes
  end

end

app/views/characters/index.html.slim
.container
  .row
    .col-md-4
    .col-md-4
      p
        / | Welcome to the characters rating home page
        / =< @message
        header
          h1 Who is your favourite champion?

      .search
        = form_tag characters_path, method: :patch do
          = text_field_tag :search, params[:search], class: "form-control", placeholder: "Champion Name"
          = submit_tag "Search", class: "btn btn-success", :name => nil
        end

.container
  .row
    .col-md-4
    .col-md-4
      h2
        | #{@character.name} (#{average_score})

.container
  .row
    .col-md-4
    .col-md-4
      img src="/champions/#{@character.image}"

.container
  .row
    .col-md-4
    .col-md-4
      = form_for @character, url: characters_url, method: :post, html: { id: "character_id" } do |f|
        .col-md-4
        .input-group
          span class="input-group-addon"
            = radio_button_tag :rating, "1"
            = label_tag "1"

            = radio_button_tag :rating, "2"
            = label_tag "2"

            = radio_button_tag :rating, "3"
            = label_tag "3"

            = radio_button_tag :rating, "4"
            = label_tag "4"

            = radio_button_tag :rating, "5"
            = label_tag "5"

          input name="character_id" type="hidden" value="#{@character._id}"

            = f.submit "Rate", class: "btn btn-success"
      end

app/views/characters/rating.html.slim
= @character.inspect

app/views/layouts/_messages.html.slim
- flash.each do |name, message|
  - if message.is_a?(String) || message.is_a?(ActiveModel::Errors)
    - notyType = (name == :notice ? "success" : "error")
    - notyTimout = (name == :notice ? 4000 : 30000)

    - if message.is_a?(ActiveModel::Errors)
      - notyText = "it's an error object"
    - else
      - notyText = message

    javascript:
      $(function() {
        noty({
          layout: 'top',
          type: "#{notyType}",
          timeout: "#{notyTimeout}",
          text: "#{notyText}"
        });
      })

app/views/layouts/application.html.slim
doctype html
html
  head
    title Champrater
    = stylesheet_link_tag "//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css", media: "all"
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  body
    header role="banner"
      nav class="navbar navbar-inverse navbar-fixed" role="navigation"
        .container-fluid
        .navbar-header
        .pull-right
          = link_to "Log Out", logout_url, method: :delete, class: "btn btn-danger logout-link" if current_user
          button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
            span class="sr-only" Toggle navigation
        a class="navbar-brand" href="#" Champion Rater
    main role="main"
      == yield
  footer
    nav class="navbar navbar-inverse navbar" role="navigation"
      .container-fluid
        .row
          .pull-left
            p.text-muted.credit
              = link_to "privacy policy", privacy_url
              | &bull;
              = link_to "terms of use", terms_url
              | &bull;
              | &copy; 2014 Champion Ratings
          .pull-right
            a href="http://euw.leagueoflegends.com/"
              == image_tag "logobanner.jpg", height:"50", width: "125"

app/views/password/edit.html.slim
= form_for @user, url: reset_url(@user.code), method: :patch, html: { id: "resetform"} do |f|
  fieldset
    legend Choose a new password
    .form-group
      = f.label :password, class: "sr-only"
      = f.password_field :password, class: "form-control", placeholder: "New Password"
    .form-group
      = f.label :password_confirmation, class: "sr-only"
      = f.password_field :password_confirmation, class: "form-control", placeholder: "Type it again"
    .form-group
      = f.submit "Update Password", class: "btn btn-success"

app/views/session/new.html.slim
.container
  .row
    .col-xs-12.col-md-12
      h1 Champion Ratings
.container
  .row
    .col-xs-4.col-md-4
    .col-xs-4.col-md-4
      = form_for :user, url: login_url, html: {id: "loginform:"} do |f|
        fieldset
          legend Please sign in
          .form-group
            = flash.map {|key, value| "#{key.capitalize}: #{value}"}.join(";")
          .form-group
            = f.label :email, class: "sr-only"
            = f.text_field :email, class: "form-control",placeholder: "Email address"
          .form-group
            = f.label :password, class: "sr-only"
            = f.password_field :password, class: "form-control", placeholder: "Password"
          .form-group
            = f.submit "Sign in", class: "btn btn-success"
    .col-xs-4.col-md-4

app/views/site/index.html.slim
= "Welcome, #{@current_user.email}"

p
  | Hi there (form code here)

ol
  - @users.each do |some_user|
    li
      = some_user.email

app/views/site/privacy.html.slim
p
  | privacy page

app/views/site/terms.html.slim
p
  | Terms of use

app/views/user_notifier/password_was_reset.html.slim
p
  ' Your ToddyCat password has been reset.
  ' If you did not reset it, please contact us.

p
  | Thanks!
  br
  | ToddyCat <(=^_^=)>

app/views/user_notifier/password_was_reset.text.erb
Your ToddyCat password has been reset. If you did not reset it, please contact us.

Thanks!
ToddyCat <(=^_^=)>

app/views/user_notifier/reset_password.html.erb
We received a request to reset your Champ Rater credentials. To do so, please follow the coded link below:

<%= reset_url(@user.code) %>

If you received this email in error, simply do nothing. The above link will expire at
<%= @user.expires_at.strftime("%-I:%M on %a, %-d %b %Y") %>

Thanks!
Champ Rater

app/views/user_notifier/reset_password.html.slim
p
  ' We receieved a request to reset your Champ Rater credentials
  ' Please follow the coded link below

p
  = link_to reset_url(@user.code), reset_url(@user.code)

p
  ' If you received this email in error, simply do nothing.  The above link
  ' will expire at #{@user.expires_at.strftime("%-I:%M on %a, %-d %b %Y")}

p
  ' Thanks!
  br
  ' Champ Rater

app/views/user_notifier/reset_password.text.erb
We received a request to reset your Champ Rater credentials. To do so, please follow the coded link below:

<%= reset_url(@user.code) %>

If you received this email in error, simply do nothing. The above link will expire at
<%= @user.expires_at.strftime("%-I:%M on %a, %-d %b %Y") %>

Thanks!
Champ Rater